version: "3.4"

networks:
  grafana: {}

services:
  grafana:
    container_name: grafana
    image: grafana/grafana:9.5.2
    environment:
      GF_INSTALL_PLUGINS: "flant-statusmap-panel"
      GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: /var/lib/grafana/dashboards/docker/docker-monitoring_rev1.json
    ports:
      - "80:3000"
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - grafana-data:/var/lib/grafana
    restart: always
    networks:
      grafana: null

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.0
    container_name: cadvisor
    privileged: true
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    restart: always
    devices:
      - /dev/kmsg
    networks:
      grafana: null

  loki:
    command: -config.file=/etc/loki/loki-config.yml
    container_name: loki
    image: grafana/loki:2.3.0
    networks:
      grafana: null
    ports:
    - 3100:3100
    restart: always
    volumes:
    - ./loki/loki-config.yml:/etc/loki/loki-config.yml

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.37.8
    ports:
      - "9090:9090"
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prom-data:/prometheus
    restart: always
    networks:
      grafana: null

  promtail:
    command: -config.file=/etc/promtail/promtail-config.yml
    container_name: promtail
    image: grafana/promtail:2.3.0
    networks:
      grafana: null
    ports:
    - protocol: tcp
      published: 1514
      target: 1514
    - protocol: tcp
      published: 9080
      target: 9080
    restart: always
    volumes:
    - ./promtail/promtail-config.yml:/etc/promtail/promtail-config.yml:ro

volumes:
  grafana-data:
  prom-data: