version: "3.4 "

networks:
  grafana: {}

services:
  grafana:
    container_name: grafana
    image: grafana/grafana:9.5.2
    environment:
      GF_INSTALL_PLUGINS: "flant-statusmap-panel"
      GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: /var/lib/grafana/dashboards/docker/cadvisor-exporter_rev1.json
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - grafana-data:/var/lib/grafana
    restart: always
    ports:
      - "80:3000"
    networks:
      grafana: null

  cadvisor:
    container_name: cadvisor
    image: gcr.io/cadvisor/cadvisor:v0.47.0
    privileged: true
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
    restart: unless-stopped
    ports:
      - 8080:8080
    networks:
      grafana: null

  loki:
    container_name: loki
    image: grafana/loki:2.3.0
    command: 
      - -config.file=/etc/loki/loki-config.yml
    volumes:
      - ./loki/loki-config.yml:/etc/loki/loki-config.yml
      - loki-data:/data/loki
    restart: always
    ports:
      - 3100:3100
    networks:
      grafana: null
    
  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.37.8
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=30d'
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prom-data:/prometheus
    restart: always
    ports:
      - 9090:9090
    networks:
      grafana: null

  promtail:
    container_name: promtail
    image: grafana/promtail:2.3.0
    command:
      - -config.file=/etc/promtail/promtail-config.yml
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./promtail/promtail-config.yml:/etc/promtail/promtail-config.yml:ro        
    restart: always
    networks:
      grafana: null  

  node-exporter:
    container_name: node-exporter
    image: prom/node-exporter:latest
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    restart: unless-stopped
    expose:
      - 9100
    networks:
      grafana: null 
  
volumes:
  grafana-data:
  prom-data:
  loki-data: