{
 "title": "Alerts - Linux Nodes",
 "description": "Alerts for Linux Nodes using prometheus and node_exporter. You can have alerts for Disk space, CPU and Memory. Also added a log of alerts and alert status.",
 "tags": [
  "alerts",
  "linux"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "Current Alerts Status",
   "type": "alertlist",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Linux Nodes Disk Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\"})",
     "legendFormat": "{{instance}} - {{mountpoint}}"
    }
   ]
  },
  {
   "title": "Linux Nodes CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\", instance=~\".+\"}[1m])) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Linux Nodes Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100*(node_memory_MemTotal_bytes - node_memory_MemFree_bytes - node_memory_Buffers_bytes - node_memory_Cached_bytes) / node_memory_MemTotal_bytes ",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}