version: "3.3"

networks:
  grafana: {}

services:
  promtail:
    container_name: promtail
    image: grafana/promtail:latest
    entrypoint: [ "/bin/sh","-c" ]
    command:
      - |
        export HOSTNAME=$$(cat /etc/hostname)
        /usr/bin/promtail -config.file=/etc/promtail/promtail-config.yml -client.external-labels=host=$$HOSTNAME
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /etc/hostname:/etc/hostname:ro
      - ./promtail/promtail-config.yml:/etc/promtail/promtail-config.yml:ro
    restart: always
    networks:
      grafana: null

  cadvisor:
    container_name: cadvisor
    image: gcr.io/cadvisor/cadvisor:v0.47.0
    privileged: true
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
    restart: unless-stopped
    expose:
      - 8080
    networks:
      grafana: null

  node-exporter:
    container_name: node-exporter
    image: prom/node-exporter:latest
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    restart: unless-stopped
    expose:
      - 9100
    networks:
      grafana: null

  mon-proxy-nginx:
    container_name: mon-proxy-nginx
    image: tekn0ir/nginx-stream:latest
    volumes:
      - ./stream.conf.d:/opt/nginx/stream.conf.d:ro
    restart: unless-stopped
    ports:
      - 9100:9100
      - 8080:8080
    networks:
      grafana: null
